name: gcn-tsp-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - contextvars=2.4
  - coverage=5.5
  - cryptography=3.4.7
  - cuda90=1.0
  - cudatoolkit=9.0
  - cudnn=7.6.5
  - cycler=0.10.0
  - cython=0.29.23
  - dataclasses=0.8
  - decorator=5.0.6
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - entrypoints=0.3
  - freetype=2.10.4
  - gast=0.4.0
  - grpcio=1.36.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - immutables=0.15
  - importlib-metadata=3.10.0
  - intel-openmp=2020.2
  - ipykernel=5.5.3
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.3
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.9.1
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.6.2
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - nbclassic=0.2.7
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.2
  - notebook=6.3.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=0.24.2
  - pandoc=2.13
  - pandocfilters=1.4.2
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pip=21.0.1
  - prometheus_client=0.10.1
  - prompt_toolkit=1.0.15
  - protobuf=3.14.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.6.7
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=0.4.1
  - pytz=2021.1
  - pywin32=300
  - pywinpty=0.5.7
  - pyzmq=22.0.3
  - qt=5.9.7
  - requests=2.25.1
  - scikit-learn=0.20.2
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.4
  - statsmodels=0.11.1
  - tensorboard=1.12.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - tensorflow-gpu=1.12.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.4.4
  - tomlkit=0.7.0
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - pip:
    - fastprogress==0.1.18
    - tensorboardx==1.5
